-- This is what the saved data looks like after each session from the addon.
SimpleLoginTrackerDB = {
{
["date"] = "2025-11-16 14:31:18",
["herbGathering"] = 15,
["spellCombatCount"] = {
["Summon Succubus"] = 3,
["Summon Voidwalker"] = 2,
["Shadow Bolt"] = 140,
},
["zonesVisited"] = {
["Undercity"] = true,
["Thousand Needles"] = true,
["Tirisfal Glades"] = true,
["Silverpine Forest"] = true,
["Durotar"] = true,
["Arathi Highlands"] = true,
["The Barrens"] = true,
["Orgrimmar"] = true,
["Hillsbrad Foothills"] = true,
["Alterac Mountains"] = true,
},
["character"] = "Dagwood",
["eliteKills"] = 0,
["goldSpent"] = 0.8287000000000013,
["itemsLooted"] = 175,
["goldEarned"] = 6.095400000000002,
["levelsGained"] = 1,
["alchemyCreations"] = 0,
["spellProfessionCount"] = {
["Herb Gathering"] = 15,
},
["sessionDuration"] = 9314,
["zoneDurations"] = {
["Undercity"] = 289,
["Thousand Needles"] = 998,
["Tirisfal Glades"] = 421,
["Silverpine Forest"] = 47,
["Durotar"] = 89,
["Arathi Highlands"] = 1738,
["The Barrens"] = 635,
["Orgrimmar"] = 92,
["Hillsbrad Foothills"] = 2727,
["Alterac Mountains"] = 2277,
},
["startLevel"] = 33,
["questsTurnedIn"] = 10,
["jumpCount"] = 1030,
["goldNetChange"] = -16.4336,
["kills"] = 112,
},
}
